apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ""
  namespace: ""
  labels:
    created-by: ""
    managed-by: "" # Used for filtering of StatefulSets created by the controller.
  ownerReferences: # Used for finding which Zookeeper this StatefulSet belongs to.
    - apiVersion: apps/v1
      kind: Zookeeper
      name: ""
      uid: ""
spec:
  selector:
    matchLabels:
      app: "" # Has to match .spec.template.metadata.labels.
  serviceName: "" # Has to be the headless service.
  replicas: 3 # By default is 1.
  template:
    metadata:
      labels:
        app: "" # Has to match .spec.selector.matchLabels.
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: ""
          image: ""
          imagePullPolicy: Always
          env:
            - name: _JAVA_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: "" # ConfigMap name set in controller.
                  key: "" # java_options key set in controller.
            - name: ZOO_DATADIR_AUTOCREATE_DISABLE
              value: "1"
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: quorum
            - containerPort: 3888
              name: election
            - containerPort: 7000
              name: metrics
            - containerPort: 8080
              name: admin
          readinessProbe:
            exec:
              command:
                - "bin/health.sh"
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - "bin/health.sh"
            initialDelaySeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: config
              mountPath: "/opt/zookeeper/conf"
              readOnly: true
            - name: data-dir
              mountPath: "/tmp/zookeeper"
      volumes:
        - name: config
          configMap:
            name: zookeeper-config
            items:
              - key: "log4j.properties"
                path: "log4j.properties"
              - key: "zoo.cfg"
                path: "zoo.cfg"
              - key: "zoo.cfg.dynamic"
                path: "zoo.cfg.dynamic"
  volumeClaimTemplates:
    - metadata:
        name: data-dir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "gp2"
        resources:
          requests:
            storage: 80Gi
