apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zookeepers.zookeeper.strataform.github.com
spec:
  group: zookeeper.strataform.github.com
  names:
    plural: zookeepers
    singular: zookeeper
    kind: Zookeeper
    shortNames:
      - zk
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      additionalPrinterColumns:
        - name: Desired Members
          type: integer
          description: The number of desired Zookeeper ensemble members
          jsonPath: .spec.replicas
        - name: Ready Members
          type: integer
          description: The number of ready Zookeeper ensemble members
          jsonPath: .status.readyReplicas
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                replicas:
                  type: integer
            status:
              type: object
              properties:
                readyReplicas:
                  type: integer
          required: [ spec ]
