apiVersion: v1
kind: Namespace
metadata:
  name: zookeeper-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zookeeper-operator
  namespace: zookeeper-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-operator
  namespace: zookeeper-operator
spec:
  selector:
    matchLabels:
      app: zookeeper-operator
  template:
    metadata:
      labels:
        app: zookeeper-operator
    spec:
      serviceAccountName: zookeeper-operator
      containers:
        - name: zookeeper-operator
          image: strataform/zookeeper-operator:dev
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: zookeeper-operator
rules:
  - apiGroups:
      - zookeeper.strataform.github.com
    resources:
      - zookeepers
    verbs:
      - "*"
  - apiGroups:
      - zookeeper.strataform.github.com
    resources:
      - zookeepers/status
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - "create"
      - "delete"
      - "get"
      - "update"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - services
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zookeeper-operator
subjects:
  - kind: ServiceAccount
    name: zookeeper-operator
    namespace: zookeeper-operator
roleRef:
  kind: ClusterRole
  name: zookeeper-operator
  apiGroup: ""
